// Code generated by Kitex v0.2.0. DO NOT EDIT.

package ecommerceaccount

import (
	"context"
	"github.com/XiaoXinTao/goproject/account_rpc/kitex_gen/xintao/project/ecommerce"
	"github.com/cloudwego/kitex/client"
	"github.com/cloudwego/kitex/client/callopt"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	Login(ctx context.Context, req *ecommerce.LoginRequest, callOptions ...callopt.Option) (r *ecommerce.LoginResponse, err error)
	Logout(ctx context.Context, req *ecommerce.LogoutRequest, callOptions ...callopt.Option) (r *ecommerce.LogoutResponse, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfo(), options...)
	if err != nil {
		return nil, err
	}
	return &kEcommerceAccountClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kEcommerceAccountClient struct {
	*kClient
}

func (p *kEcommerceAccountClient) Login(ctx context.Context, req *ecommerce.LoginRequest, callOptions ...callopt.Option) (r *ecommerce.LoginResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.Login(ctx, req)
}

func (p *kEcommerceAccountClient) Logout(ctx context.Context, req *ecommerce.LogoutRequest, callOptions ...callopt.Option) (r *ecommerce.LogoutResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.Logout(ctx, req)
}
